add lists solution
Leenday/ru-study-python pull request #1
Opened 2023-06-20 10:59 UTC by Leenday

2023-06-22 06:29 UTC, aleksandr-semenov-dbp requested changes

2023-06-22 06:29 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        list_center_index = int(len(input_list) / 2)
`int(x / 2) == x // 2`

2023-06-22 06:29 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +    def recurcive_search(input_list: list[int], query: int, indexes: list[int]) -> int:
Подход оригинальный, но использование дополнительного списка не очень эффективно, на практике так делать нельзя. Нужно обойтись просто дополнительным числом, например смещением обрабатываемого списка в исходном

2023-06-22 13:27 UTC, Leenday commented on lists/lists.py
> +        list_center_index = int(len(input_list) / 2)
Спасибо, так намного лучше

2023-06-22 13:28 UTC, Leenday commented on lists/lists.py
> +    def recurcive_search(input_list: list[int], query: int, indexes: list[int]) -> int:
Изменил логику, спасибо за идею

2023-06-23 08:26 UTC, aleksandr-semenov-dbp approved these changes

2023-06-23 16:21 UTC, merged