add solution to maps exercises
Leenday/ru-study-python pull request #2
Opened 2023-06-20 16:34 UTC by Leenday

2023-06-22 06:31 UTC, aleksandr-semenov-dbp requested changes

2023-06-22 06:31 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +        if len(movie["country"].split(",")) >= 2 and float(movie["rating_kinopoisk"]) > 0:
подсчет запятых split-ом неэффективен

2023-06-22 13:27 UTC, Leenday commented on maps/maps.py
> +        if len(movie["country"].split(",")) >= 2 and float(movie["rating_kinopoisk"]) > 0:
Сменил логику на подсчет запятых, без подсчета длины результирующего массива.
Как эффективнее считать слова?

2023-06-23 08:31 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +        if len(movie["country"].split(",")) >= 2 and float(movie["rating_kinopoisk"]) > 0:
Зависит от определения слова, скорее всего придется применять что-то из модуля re. В наших задачах вроде бы не требуется.

2023-06-23 08:32 UTC, aleksandr-semenov-dbp approved these changes

2023-06-28 06:34 UTC, merged