add solution to filter_map exercise
Leenday/ru-study-python pull request #3
Opened 2023-06-21 06:06 UTC by Leenday

2023-06-22 06:34 UTC, aleksandr-semenov-dbp requested changes

2023-06-22 06:34 UTC, aleksandr-semenov-dbp commented on filter_map/filter_map.py
> +                result += [res]
.append()?

2023-06-22 13:30 UTC, Leenday commented on filter_map/filter_map.py
> +                result += [res]
Почему бы и нет)

2023-06-23 08:33 UTC, aleksandr-semenov-dbp approved these changes

2023-06-28 06:34 UTC, merged